#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
case="TestCaseFSI-V1.6ext"

tutorialPath=`dirname $0`/..
. $WM_PROJECT_DIR/bin/tools/RunFunctions

(cd $case; exec setSet -case fluid -batch fluid/batch.setSet)
(cd $case; exec setsToZones -case fluid -noFlipMap)
(cd $case; exec setSet -case solid -batch solid/batch.setSet)
(cd $case; exec setsToZones -case solid -noFlipMap)
(cd $case; ./makeSerialLinks fluid solid)
(cd $case/fluid; exec $application)
